### ISSUE TITLE
Capstone project Kanban

### ISSUE THREAD

**Issue by luis-pomare** [luis-pomare/rails-car-booking-rentals-backend#20]
This is the link to our Kanban board:
https://github.com/users/luis-pomare/projects/4

We are 4 people working on this project so we decided to implement the nine first project requirements.

Here is a screenshot attached
![image](https://github.com/luis-pomare/rails-car-booking-rentals-backend/assets/18634639/d678e732-6175-44b9-b24e-5d422ab44c37)

**Comment by Meltrust** [comment]
Hi @luis-pomare

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not include a screenshot of the kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi @luis-pomare,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have been assigned.✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] At the time of this review, these are the pointings:

@luis-pomare 13
@Alejandro-Bernal-M 14
@Balikuddembe 16
@shayan1234554321 10

The general [requirement ](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)is that no one may have more than 5 points than any team member:

![image](https://github.com/luis-pomare/rails-car-booking-rentals-backend/assets/57421823/49cb6151-f50d-426c-86ab-056c10f87f85)


@shayan1234554321 has too few points compared to the other team members.

Kindly, ensure that the maximum difference in points among members is no more than 5.

That way, we will meet this particular requirement.

_Tip: Move the numbers, and/or reassign some tasks._ 



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alejandro-Bernal-M** [comment]
Corrected!

**Comment by Meltrust** [comment]
Hi @Alejandro-Bernal-M,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

 ## Required Changes ♻️

- [ ] At the time of this re-review, these are the pointings:

@luis-pomare 13
@Alejandro-Bernal-M 14
@Balikuddembe 10
@shayan1234554321 16

@shayan1234554321 now has 16 points.  @Balikuddembe has just 10.  16-10 = 6.  The requirement says "no more or less than _FIVE_ points", but 6>5.

In order to meet the requirement, please make it so nobody has more than 5 points than each other.  If you need help achieving this, I'm available to help on Slack.

_Tip:  Just give an extra point to @Balikuddembe  OR take one point from @shayan1234554321 and you will meet the requirement._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alejandro-Bernal-M** [comment]
We made a mistake, now is corrected :)

**Comment by Meltrust** [comment]
> We made a mistake, now is corrected :)

It still needs correction.  I can't approve the project in this state.  Please contact me on Slack.  If you don't respond, I'll be forced to request changes.  Kindly respond on Slack I can help.

_note:  The student responded on Slack and he successfully corrected the pointings.  Approving._

**Comment by Meltrust** [comment]
Hi @Alejandro-Bernal-M,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- The pointings are now fair, and meet the requirement✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
